/**
 * PDF generation for Command Center (CC-3)
 *
 * Consolidates all 7 executive blocks into a single PDF document.
 * Uses lazy-loaded jsPDF + jspdf-autotable (~200KB loaded only on click).
 * Pattern follows generateReportPDF.ts and generateMetricsPDF.ts.
 */

import type {
  CommandCenterMetrics,
  LeaderboardEntry,
  ProspectingSummary,
  TemperatureBreakdown,
  DealTypeSplit,
  PulseStatus,
} from '@/features/command-center/hooks/useCommandCenterMetrics'
import type { Alert } from '@/features/command-center/utils/alert-rules'
import type { PulseColor } from '@/features/command-center/utils/pulse-rules'

type RGB = [number, number, number]

const COLORS: Record<string, RGB> = {
  primary: [15, 23, 42],
  secondary: [100, 116, 139],
  blue: [59, 130, 246],
  emerald: [16, 185, 129],
  purple: [139, 92, 246],
  orange: [249, 115, 22],
  red: [239, 68, 68],
  amber: [245, 158, 11],
  bgLight: [248, 250, 252],
  border: [226, 232, 240],
  white: [255, 255, 255],
}

const SEVERITY_LABELS: Record<string, string> = {
  critical: 'CRITICO',
  high: 'ALTO',
  medium: 'MEDIO',
  low: 'BAIXO',
}

const PULSE_LABELS: Record<PulseColor, string> = {
  green: 'Verde',
  yellow: 'Amarelo',
  red: 'Vermelho',
}

export interface CommandCenterPDFData {
  pipelineValue: number
  generatedCommission: number
  dealTypeSplit: DealTypeSplit
  winRate: number
  activeContacts: number
  prospectingSummary: ProspectingSummary
  avgSalesCycle: number
  temperatureBreakdown: TemperatureBreakdown
  pulse: PulseStatus
  changes: { pipeline: number; deals: number; winRate: number; revenue: number }
  funnelData: { name: string; count: number }[]
  leaderboard: LeaderboardEntry[]
  alerts: Alert[]
  wonRevenue: number
}

export interface GenerateCommandCenterPDFOptions {
  data: CommandCenterPDFData
  period: string
  boardName?: string
  generatedBy?: string
  isAdminOrDirector: boolean
}

function formatCurrency(value: number): string {
  if (value >= 1000000) return `R$${(value / 1000000).toFixed(1)}M`
  if (value >= 1000) return `R$${(value / 1000).toFixed(0)}k`
  return `R$${value.toLocaleString('pt-BR')}`
}

export async function generateCommandCenterPDF(options: GenerateCommandCenterPDFOptions): Promise<void> {
  const { data, period, boardName, generatedBy, isAdminOrDirector } = options

  // Lazy load — keeps jsPDF out of the main bundle (~200KB)
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  const autoTable = autoTableModule.default

  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.width
  const pageHeight = doc.internal.pageSize.height
  const margin = 15
  const contentWidth = pageWidth - margin * 2

  const now = new Date()
  const dateStr = now.toLocaleDateString('pt-BR')
  const timeStr = now.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })
  const fileDate = now.toISOString().slice(0, 10)

  // Helper: ensure space for next section, add page if needed
  function ensureSpace(y: number, needed: number): number {
    if (y + needed > pageHeight - 25) {
      doc.addPage()
      return 20
    }
    return y
  }

  // ════════════════════════════════════════════
  // SECTION 1 — Header
  // ════════════════════════════════════════════
  doc.setFillColor(...COLORS.blue)
  doc.roundedRect(margin, 12, 12, 12, 2, 2, 'F')
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('Z', margin + 4.5, 20)

  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.primary)
  doc.text('Central de Comando', margin + 18, 19)

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...COLORS.secondary)
  doc.text('ZmobCRM', margin + 18, 24)

  // Period badge
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  const periodText = `${period} | ${boardName || 'Pipeline Padrao'}`
  const badgeWidth = doc.getTextWidth(periodText) + 16
  const badgeX = pageWidth - margin - badgeWidth
  doc.setFillColor(...COLORS.primary)
  doc.roundedRect(badgeX, 14, badgeWidth, 12, 2, 2, 'F')
  doc.setTextColor(255, 255, 255)
  doc.text(periodText, badgeX + 8, 21.5)

  // Generated by
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...COLORS.secondary)
  doc.text(`Por: ${generatedBy || 'Usuario'} | ${dateStr} as ${timeStr}`, pageWidth - margin, 32, { align: 'right' })

  // Divider
  doc.setDrawColor(...COLORS.border)
  doc.setLineWidth(0.3)
  doc.line(margin, 36, pageWidth - margin, 36)

  let y = 43

  // ════════════════════════════════════════════
  // SECTION 2 — KPI Cards (2 columns x 4 rows)
  // ════════════════════════════════════════════
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.primary)
  doc.text('Indicadores-Chave', margin, y)
  y += 6

  const totalClosedDeals = data.dealTypeSplit.VENDA.count + data.dealTypeSplit.LOCACAO.count

  const kpis = [
    { label: 'VGV Pipeline', value: formatCurrency(data.pipelineValue), change: `${data.changes.pipeline >= 0 ? '+' : ''}${data.changes.pipeline.toFixed(1)}%`, accent: COLORS.blue },
    { label: 'Comissao Gerada', value: formatCurrency(data.generatedCommission), change: `${data.changes.revenue >= 0 ? '+' : ''}${data.changes.revenue.toFixed(1)}%`, accent: COLORS.emerald },
    { label: `Fechados ${data.dealTypeSplit.VENDA.count}V / ${data.dealTypeSplit.LOCACAO.count}L`, value: `${totalClosedDeals}`, change: `${data.changes.deals >= 0 ? '+' : ''}${data.changes.deals.toFixed(1)}%`, accent: COLORS.purple },
    { label: 'Conversao', value: `${data.winRate.toFixed(1)}%`, change: `${data.changes.winRate >= 0 ? '+' : ''}${data.changes.winRate.toFixed(1)}%`, accent: COLORS.orange },
    { label: 'Contatos Ativos', value: `${data.activeContacts}`, change: `${data.temperatureBreakdown.hot} HOT`, accent: [6, 182, 212] as RGB },
    { label: 'Ligacoes / Conexao', value: `${data.prospectingSummary.totalCalls}`, change: `${data.prospectingSummary.connectionRate.toFixed(1)}% conexao`, accent: COLORS.orange },
    { label: 'Ciclo Medio', value: `${data.avgSalesCycle} dias`, change: 'tempo fechamento', accent: [236, 72, 153] as RGB },
    { label: 'Saude Carteira', value: `${data.temperatureBreakdown.hot + data.temperatureBreakdown.warm + data.temperatureBreakdown.cold}`, change: `${data.temperatureBreakdown.hot}HOT ${data.temperatureBreakdown.warm}WARM ${data.temperatureBreakdown.cold}COLD`, accent: [20, 184, 166] as RGB },
  ]

  const cols = 2
  const cardGap = 4
  const cardWidth = (contentWidth - cardGap * (cols - 1)) / cols
  const cardHeight = 24

  kpis.forEach((kpi, i) => {
    const col = i % cols
    const row = Math.floor(i / cols)
    const x = margin + col * (cardWidth + cardGap)
    const yPos = y + row * (cardHeight + cardGap)

    doc.setFillColor(...COLORS.white)
    doc.setDrawColor(...COLORS.border)
    doc.roundedRect(x, yPos, cardWidth, cardHeight, 2, 2, 'FD')

    // Colored left border
    doc.setFillColor(...kpi.accent)
    doc.rect(x, yPos + 2, 2.5, cardHeight - 4, 'F')

    doc.setFontSize(6.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...COLORS.secondary)
    doc.text(kpi.label.toUpperCase(), x + 6, yPos + 6)

    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...COLORS.primary)
    doc.text(kpi.value, x + 6, yPos + 14)

    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...COLORS.secondary)
    doc.text(kpi.change, x + 6, yPos + 20)
  })

  y += Math.ceil(kpis.length / cols) * (cardHeight + cardGap) + 6

  // ════════════════════════════════════════════
  // SECTION 3 — Forecast Bar
  // ════════════════════════════════════════════
  y = ensureSpace(y, 25)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.primary)
  doc.text('Meta / Forecast', margin, y)
  y += 6

  const actual = data.wonRevenue
  const goal = data.pipelineValue > 0 ? data.pipelineValue : 1
  const pct = Math.min((actual / goal) * 100, 100)

  // Progress bar background
  doc.setFillColor(...COLORS.bgLight)
  doc.setDrawColor(...COLORS.border)
  doc.roundedRect(margin, y, contentWidth, 10, 2, 2, 'FD')

  // Progress bar fill
  const fillWidth = Math.max((pct / 100) * contentWidth, 2)
  const barColor: RGB = pct >= 80 ? COLORS.emerald : pct >= 40 ? COLORS.amber : COLORS.red
  doc.setFillColor(...barColor)
  doc.roundedRect(margin, y, fillWidth, 10, 2, 2, 'F')

  // Text on bar
  doc.setFontSize(7)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.primary)
  doc.text(`Realizado: ${formatCurrency(actual)} / Meta: ${formatCurrency(goal)} — ${pct.toFixed(0)}%`, margin + 4, y + 6.5)

  y += 18

  // ════════════════════════════════════════════
  // SECTION 4 — Funnel Table
  // ════════════════════════════════════════════
  y = ensureSpace(y, 30)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.primary)
  doc.text('Funil de Vendas', margin, y)
  y += 3

  const funnelBody = data.funnelData.length > 0
    ? data.funnelData.map(stage => [stage.name, String(stage.count)])
    : [['Sem dados', '—']]

  autoTable(doc, {
    startY: y,
    head: [['Estagio', 'Contatos']],
    body: funnelBody,
    theme: 'striped',
    tableWidth: contentWidth,
    margin: { left: margin, right: margin },
    styles: { font: 'helvetica', fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: COLORS.blue, textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: COLORS.bgLight },
    columnStyles: { 1: { halign: 'center', cellWidth: 30 } },
  })

  // Get finalY from autoTable
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10

  // ════════════════════════════════════════════
  // SECTION 5 — Broker Ranking
  // ════════════════════════════════════════════
  y = ensureSpace(y, 30)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.primary)
  doc.text('Ranking de Corretores', margin, y)
  y += 3

  const rankingData = isAdminOrDirector
    ? data.leaderboard.slice(0, 10)
    : data.leaderboard.slice(0, 1) // Non-admin: only own data (first entry)

  const rankingBody = rankingData.length > 0
    ? rankingData.map((entry, i) => [
        String(i + 1),
        entry.ownerName,
        `${entry.wonCount}`,
        formatCurrency(entry.wonValue),
        `${entry.totalCalls}`,
      ])
    : [['—', 'Sem dados', '—', '—', '—']]

  autoTable(doc, {
    startY: y,
    head: [['#', 'Corretor', 'Negocios', 'Comissao', 'Ligacoes']],
    body: rankingBody,
    theme: 'striped',
    tableWidth: contentWidth,
    margin: { left: margin, right: margin },
    styles: { font: 'helvetica', fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: COLORS.primary, textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: COLORS.bgLight },
    columnStyles: {
      0: { halign: 'center', cellWidth: 12 },
      1: { cellWidth: 'auto' },
      2: { halign: 'center', cellWidth: 22 },
      3: { halign: 'right', fontStyle: 'bold' },
      4: { halign: 'center', cellWidth: 22 },
    },
  })

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10

  // ════════════════════════════════════════════
  // SECTION 6 — Wallet + Prospecting
  // ════════════════════════════════════════════
  y = ensureSpace(y, 40)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.primary)
  doc.text('Carteira & Prospeccao', margin, y)
  y += 6

  // Wallet card
  const halfWidth = (contentWidth - 6) / 2

  doc.setFillColor(...COLORS.bgLight)
  doc.setDrawColor(...COLORS.border)
  doc.roundedRect(margin, y, halfWidth, 30, 2, 2, 'FD')

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.primary)
  doc.text('Distribuicao Carteira', margin + 4, y + 6)

  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...COLORS.secondary)
  const totalContacts = data.temperatureBreakdown.hot + data.temperatureBreakdown.warm + data.temperatureBreakdown.cold
  doc.text(`Total: ${totalContacts} contatos ativos`, margin + 4, y + 12)
  doc.text(`HOT: ${data.temperatureBreakdown.hot}  |  WARM: ${data.temperatureBreakdown.warm}  |  COLD: ${data.temperatureBreakdown.cold}`, margin + 4, y + 18)
  doc.text(`Ativos: ${data.activeContacts}`, margin + 4, y + 24)

  // Prospecting card
  const rightX = margin + halfWidth + 6
  doc.setFillColor(...COLORS.bgLight)
  doc.setDrawColor(...COLORS.border)
  doc.roundedRect(rightX, y, halfWidth, 30, 2, 2, 'FD')

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.primary)
  doc.text('Prospeccao', rightX + 4, y + 6)

  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...COLORS.secondary)
  doc.text(`Ligacoes: ${data.prospectingSummary.totalCalls}`, rightX + 4, y + 12)
  doc.text(`Taxa Conexao: ${data.prospectingSummary.connectionRate.toFixed(1)}%`, rightX + 4, y + 18)
  doc.text(`Agendamentos: ${data.prospectingSummary.scheduledMeetings}  |  Propostas: ${data.prospectingSummary.proposalsSent}`, rightX + 4, y + 24)

  y += 38

  // ════════════════════════════════════════════
  // SECTION 7 — Alerts
  // ════════════════════════════════════════════
  y = ensureSpace(y, 30)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.primary)
  doc.text('Alertas', margin, y)
  y += 3

  const filteredAlerts = isAdminOrDirector
    ? data.alerts
    : data.alerts.filter(a => a.type !== 'underperforming_brokers')

  const alertBody = filteredAlerts.length > 0
    ? filteredAlerts.map(a => [SEVERITY_LABELS[a.severity] || a.severity, a.message])
    : [['—', 'Nenhum alerta no periodo']]

  autoTable(doc, {
    startY: y,
    head: [['Severidade', 'Descricao']],
    body: alertBody,
    theme: 'striped',
    tableWidth: contentWidth,
    margin: { left: margin, right: margin },
    styles: { font: 'helvetica', fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: COLORS.red, textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: COLORS.bgLight },
    columnStyles: {
      0: { cellWidth: 28, halign: 'center', fontStyle: 'bold' },
      1: { cellWidth: 'auto' },
    },
    didParseCell: (cellData) => {
      if (cellData.section === 'body' && cellData.column.index === 0) {
        const text = String(cellData.cell.raw)
        if (text === 'CRITICO') cellData.cell.styles.textColor = COLORS.red
        else if (text === 'ALTO') cellData.cell.styles.textColor = COLORS.orange
        else if (text === 'MEDIO') cellData.cell.styles.textColor = COLORS.amber
      }
    },
  })

  // ════════════════════════════════════════════
  // FOOTER — All pages
  // ════════════════════════════════════════════
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)

    doc.setDrawColor(...COLORS.border)
    doc.setLineWidth(0.3)
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15)

    doc.setFontSize(6.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...COLORS.secondary)
    doc.text('ZmobCRM — Confidencial', margin, pageHeight - 9)
    doc.text(`Gerado por ${generatedBy || 'Usuario'}`, pageWidth / 2, pageHeight - 9, { align: 'center' })
    doc.text(`Pagina ${i} / ${totalPages}`, pageWidth - margin, pageHeight - 9, { align: 'right' })
  }

  // ════════════════════════════════════════════
  // OUTPUT
  // ════════════════════════════════════════════
  doc.save(`central-de-comando-${fileDate}.pdf`)
}
