-- NO-OP: This migration is redundant.
-- 20260312100000_update_prospecting_filters_to_arrays.sql already uses
-- is_won/is_lost boolean flags (not status text) in the has_active_deal filter.
-- Both get_prospecting_filtered_contacts and get_prospecting_filtered_contact_ids
-- were created with the correct boolean logic from the start.
-- Kept as empty file to preserve schema_migrations history.
